export default emojis = {
  // emoji0: require('assets/images/emojis/emoji(1).png'),
  emoji1: require('assets/images/emojis/emoji(1).png'),
  emoji2: require('assets/images/emojis/emoji(2).png'),
  emoji3: require('assets/images/emojis/emoji(3).png'),
  emoji4: require('assets/images/emojis/emoji(4).png'),
  emoji5: require('assets/images/emojis/emoji(5).png'),
  emoji6: require('assets/images/emojis/emoji(6).png'),
  emoji7: require('assets/images/emojis/emoji(7).png'),
  emoji8: require('assets/images/emojis/emoji(8).png'),
  emoji9: require('assets/images/emojis/emoji(9).png'),
  emoji10: require('assets/images/emojis/emoji(10).png'),
  emoji11: require('assets/images/emojis/emoji(11).png'),
  emoji12: require('assets/images/emojis/emoji(12).png'),
  emoji13: require('assets/images/emojis/emoji(13).png'),
  emoji14: require('assets/images/emojis/emoji(14).png'),
  emoji15: require('assets/images/emojis/emoji(15).png'),
  emoji16: require('assets/images/emojis/emoji(16).png'),
  emoji17: require('assets/images/emojis/emoji(17).png'),
  emoji18: require('assets/images/emojis/emoji(18).png'),
  emoji19: require('assets/images/emojis/emoji(19).png'),
  emoji20: require('assets/images/emojis/emoji(20).png'),
  emoji21: require('assets/images/emojis/emoji(21).png'),
  emoji22: require('assets/images/emojis/emoji(22).png'),
  emoji23: require('assets/images/emojis/emoji(23).png'),
  emoji24: require('assets/images/emojis/emoji(24).png'),
};